version: '3'

services:
  network-monitor:
    container_name: network-monitor
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PACKAGE=network-monitor
        - PORT=8001
    ports:
      - '9002:8001'
  network-data:
    container_name: network-data
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PACKAGE=network-data
        - PORT=8000
    ports:
      - '9001:8000'